# -*- coding: utf-8 -*-

CHAOS = {
    '1.x': '',
    '2.x': '',
    '3.x': '',
    '4.3': '',
    '5.0': '',
    'Accessibility': '',
    'Ansible': '',
    'Bug': '',
    'Cleanup needed': '',
    'Confirmed': '',
    'Content': '',
    'Contributor profile': '',
    'Dependencies': '',
    'Design': '',
    'Difficulty-Easy': '',
    'Difficulty-Hard': '',
    'Difficulty-Moderate': '',
    'Enhancement': '',
    'Feature': '',
    'Foundation Information': '',
    'HomePage': '',
    'Important': '',
    'Jenkins Job Builder': '',
    'Jenkins VM donation': '',
    'Missing': '',
    'OSX': '',
    'PLIP': '',
    'PLIP 10359: z3cform control panel': '',
    'PLIP 13260: Remove CMF': '',
    'PLIP 13350: Edit Member Schema TTW': '',
    'PLIP 13770: Portal Tools Removal': '',
    'PLIP 13787 - Barceloneta / MainTemplate': '',
    'Priority-High': '',
    'Priority-Low': '',
    'Priority-Medium': '',
    'Question': '',
    'Regression': '',
    'Sprint': '',
    'Testing': '',
    'Tests': '',
    'Theme': '',
    'Type-Documentation': '',
    'UX Editor': '',
    'UX Integrator/Themer': '',
    'UX Site Admin': '',
    'area:accessibility': '',
    'area:documentation': '',
    'area:plone.app.widgets': '',
    'area:plone5': '',
    'area:styles': '',
    'bug': '',
    'bundle:barceloneta': '',
    'bundle:foldercontents': '',
    'bundle:toolbar': '',
    'bundle:widgets': '',
    'ci': '',
    'developer': '',
    'documentation': '',
    'duplicate': '',
    'enhancement': '',
    'feature': '',
    'feature request': '',
    'help wanted': '',
    'hosting': '',
    'important': '',
    'imported': '',
    'imported from dev.plone.org': '',
    'in progress': '',
    'invalid': '',
    'migration': '',
    'missing': '',
    'needs review': '',
    'pattern:filemanager': '',
    'pattern:modal': '',
    'pattern:pickadate': '',
    'pattern:querystring': '',
    'pattern:relateditems': '',
    'pattern:resourceregistry': '',
    'pattern:select2': '',
    'pattern:structure': '',
    'pattern:thememapper': '',
    'plog2014': '',
    'plone.app.blocks': '',
    'plone.app.standardtiles': '',
    'plone.app.tiles': '',
    'plone.tiles': '',
    'plone3': '',
    'plone4': '',
    'plone5': '',
    'pr ok': '',
    'pr orphaned': '',
    'pr p4.0': '',
    'pr p4.3': '',
    'pr p5.0': '',
    'pr rebase': '',
    'pr review': '',
    'pr testing': '',
    'pr wip': '',
    'prio:high': '',
    'prio:low': '',
    'prio:normal': '',
    'question': '',
    'ready': '',
    'regression': '',
    'regression from atct': '',
    'release': '',
    'request for comments': '',
    'skunkworks': '',
    'status:confirmed': '',
    'status:deferred': '',
    'status:feedback-needed': '',
    'status:fix-committed': '',
    'status:in-progress': '',
    'status:rejected': '',
    'status:resolved': '',
    'styleguide': '',
    'testing': '',
    'todo': '',
    'toolbar': '',
    'type:bug': '',
    'type:feature': '',
    'type:invalid': '',
    'unconfirmed': '',
    'widgets': '',
    'wineandbeersprint': '',
    'wontfix': '',
}
